name: HolyCases
version: 1.21.11
main: ru.nbk.rolecases.HolyCases
api-version: '1.21'
description: "Плагин HolyCases для кейсов с донатом на серверах Minecraft 1.21+"
softdepend: [PlaceholderAPI]
authors:
  - NBK
  - itzHiti
  - KoroLKotov
commands:
  holycases:
    aliases:
      - hc
    description: Главная команда плагина HolyCases
    usage: /holycases [give|take|setitem|givecase|remcase|reload|keys|giveallkeys]
    permission: holycases.admin
permissions:
  holycases.admin:
    description: Доступ к админ-командам плагина
    default: op
  holycases.use:
    description: Доступ к открытию кейсов
    default: true
